### PR TITLE
Update nodejs.yml

### PR DESCRIPTION
**Pull request by vilaboim**
# PR Details
Add Github Actions first config.

## Description
This config runs eslint and unit tests for every PR.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by vilaboim** [comment]
@all-contributors please add @vilaboim for doc, code and design

**Comment by stanleygomes** [comment]
@all-contributors please add @stanleygomes for code

**Comment by stanleygomes** [comment]
@all-contributors please add @rafael1995 for code

**Comment by stanleygomes** [comment]
@all-contributors please add @hugonasciutti for code

**Comment by stanleygomes** [comment]
@all-contributors please add @mkny for code

**Comment by stanleygomes** [comment]
@all-contributors please add @wendreo  for doc

**Comment by stanleygomes** [comment]
@all-contributors please add @Thiago-cantuario  for doc

**Comment by stanleygomes** [comment]
@all-contributors please add @faelribeiro22  for code

**Pull request merged**
