### PR TITLE
docs: Change documentation for Gandalf Lint

### PR DESCRIPTION
**Pull request by victormaestri**
## Description

Change documentarion about Gandalf Lint

## Types of changes

- [x] Docs change / refactoring / dependency upgrade

### CODE REVIEW

**Comment by vilaboim** [comment]
I believe the meaning is correct, I would not change.

**Comment by victormaestri** [comment]
> I believe the meaning is correct, I would not change.

So I believe it is necessary to change the gandalf-lint readme

**Comment by vilaboim** [comment]
> > I believe the meaning is correct, I would not change.
> 
> So I believe it is necessary to change the gandalf-lint readme

Why?
The sentence is "if you don't use gandalf-lint, you shall not pass", you want to change to "if you don't use gandalf-lint, bad code shall not pass", I believe it doesn't make sense.

**Comment by victormaestri** [comment]
> > > I believe the meaning is correct, I would not change.
> > 
> > 
> > So I believe it is necessary to change the gandalf-lint readme
> 
> Why?
> The sentence is "if you don't use gandalf-lint, you shall not pass", you want to change to "if you don't use gandalf-lint, bad code shall not pass", I believe it doesn't make sense.

Ok, I believe you are right.

**Pull request closed without merging**
